#!/usr/bin/env ruby

site 'http://community.opscode.com/api/v1'

cookbook 'homebrew'
cookbook 'dmg'
cookbook 'mac_os_x'

cookbook 'vim',  :git => 'git://github.com/pawelpacana/vim-cookbook'
cookbook 'curl', :git => 'git://github.com/mbl-cli/curl-cookbook'

cookbook 'firefox',       :path => 'vendor/cookbooks/firefox'
cookbook 'google-chrome', :path => 'vendor/cookbooks/google-chrome'
cookbook 'ack',           :path => 'vendor/cookbooks/ack'
cookbook 'libxml2',       :path => 'vendor/cookbooks/libxml2'
cookbook 'ctags',         :path => 'vendor/cookbooks/ctags'
cookbook 'git',           :path => 'vendor/cookbooks/git'
cookbook 'bash',          :path => 'vendor/cookbooks/bash'
cookbook 'wget',          :path => 'vendor/cookbooks/wget'
cookbook 'rvm',           :path => 'vendor/cookbooks/rvm'
cookbook 'netcat',        :path => 'vendor/cookbooks/netcat'
cookbook 'socat',         :path => 'vendor/cookbooks/socat'
cookbook 'findutils',     :path => 'vendor/cookbooks/findutils'
cookbook 'coreutils',     :path => 'vendor/cookbooks/coreutils'
