#!/usr/bin/env ruby

site 'http://community.opscode.com/api/v1'

cookbook 'homebrew'
cookbook 'dmg'
cookbook 'mac_os_x'

cookbook 'vim',  :git => 'git://github.com/pawelpacana/vim-cookbook'
cookbook 'curl', :git => 'git://github.com/mbl-cli/curl-cookbook'

cookbook 'firefox',       :path => 'vendor/cookbooks/firefox'
cookbook 'google-chrome', :path => 'vendor/cookbooks/google-chrome'
