#!/bin/bash

HOSTNAME=$(hostname)
CHEFDK_DOWNLOAD_URL='https://opscode-omnibus-packages.s3.amazonaws.com/mac_os_x/10.9/x86_64/chefdk-0.2.0-2.dmg'

set -e
set -x

if [[ ! -x /usr/bin/chef-solo ]]; then
  curl $CHEFDK_DOWNLOAD_URL --progress -o /tmp/chef.dmg
  hdiutil attach /tmp/chef.dmg
  sudo installer -pkg /Volumes/chefdk/chefdk.pkg -target /
  hdiutil detach /Volumes/chefdk
fi

if [[ -d tmp/cookbooks ]]; then 
  rm -rf tmp/cookbooks/
fi

if [[ ! -d /usr/local ]]; then
  sudo mkdir /usr/local
  sudo chown -R `whoami`:staff /usr/local
fi

if [[ ! -d /opt/homebrew-cask/ ]]; then
  sudo mkdir /opt/homebrew-cask
  sudo chown -R `whoami`:staff /opt/homebrew-cask
fi

if ! pkgutil --pkg-info=com.apple.pkg.CLTools_Executables > /dev/null; then
  softwareupdate -v -i -r
fi

berks vendor tmp/cookbooks/
chef-solo -c config/solo.rb -j nodes/${HOSTNAME}.json
