name             'java_osx'
maintainer       ''
maintainer_email ''
license          ''
description      'Installs/Configures java_osx'
long_description 'Installs/Configures java_osx'
version          '0.1.0'

depends 'dmg'
depends 'homebrew'
